# installer for orcas skin

from setup import ExtensionInstaller

def loader():
    return OrcasInstaller()

class OrcasInstaller(ExtensionInstaller):
    def __init(self):
        super(OrcasInstaller, self).__init__(
            version="1.6",
            name='orcas',
            description='Skin for Orcas weather station',
            author='Bill Madill',
            author_email'bill@jamimi.com',
            config={
                'StdReport': {
                    'orcas': {
                        'skin':'orcas',
                        'enable':'true'}}},
            files=[('skins/orcas',
                    ['skins/orcas/weather-current.inc',
                     'skins/orcas/skin.conf',
                     'skins/orcas/about.html.tmpl',
                     'skins/orcas/favicon.ico',
                     'skins/orcas/almanac.html.tmpl',
                     'skins/orcas/weather-summaries-monthly.inc',
                     'skins/orcas/index.html.tmpl',
                     'skins/orcas/weather-week.inc',
                     'skins/orcas/weather-month.inc',
                     'skins/orcas/forecast.html.tmpl',
                     'skins/orcas/footer.inc',
                     'skins/orcas/robots.txt',
                     'skins/orcas/weather-year.inc',
                     'skins/orcas/header.inc',
                     'skins/orcas/weather-summaries-yearly.inc']),
                   ('skins/orcas/NOAA',
                    ['skins/orcas/NOAA/NOAA-YYYY.txt.tmpl',
                     'skins/orcas/NOAA/NOAA-YYYY-MM.txt.tmpl']),
                   ('skins/orcas/css',
                    ['skins/orcas/css/foundation_stock.css',
                     'skins/orcas/css/app.css',
                     'skins/orcas/css/foundation_stock.min.css',
                     'skins/orcas/css/foundation.min.css',
                     'skins/orcas/css/normalize.css',
                     'skins/orcas/css/foundation.css']),
                   ('skins/orcas/images',
                    ['skins/orcas/images/icons']),
                   ('skins/orcas/images/icons',
                    ['skins/orcas/images/icons/triangle-down.png',
                     'skins/orcas/images/icons/AF.png',
                     'skins/orcas/images/icons/K.png',
                     'skins/orcas/images/icons/sleet.png',
                     'skins/orcas/images/icons/BK.png',
                     'skins/orcas/images/icons/snowflake.png',
                     'skins/orcas/images/icons/H.png',
                     'skins/orcas/images/icons/flag.png',
                     'skins/orcas/images/icons/thermometer.png',
                     'skins/orcas/images/icons/CL.png',
                     'skins/orcas/images/icons/raintorrent.png',
                     'skins/orcas/images/icons/SCn.png',
                     'skins/orcas/images/icons/tstms.png',
                     'skins/orcas/images/icons/N.png',
                     'skins/orcas/images/icons/SW.png',
                     'skins/orcas/images/icons/CLn.png',
                     'skins/orcas/images/icons/moonphase.png',
                     'skins/orcas/images/icons/sprinkles.png',
                     'skins/orcas/images/icons/B1n.png',
                     'skins/orcas/images/icons/FW.png',
                     'skins/orcas/images/icons/SC.png',
                     'skins/orcas/images/icons/OVn.png',
                     'skins/orcas/images/icons/rainshwrs.png',
                     'skins/orcas/images/icons/thermometer-dewpoint.png',
                     'skins/orcas/images/icons/snow.png',
                     'skins/orcas/images/icons/raindrop.png',
                     'skins/orcas/images/icons/flag-yellow.png',
                     'skins/orcas/images/icons/SE.png',
                     'skins/orcas/images/icons/BKn.png',
                     'skins/orcas/images/icons/moon.png',
                     'skins/orcas/images/icons/PF.png',
                     'skins/orcas/images/icons/sunriseset.png',
                     'skins/orcas/images/icons/F+.png',
                     'skins/orcas/images/icons/water.png',
                     'skins/orcas/images/icons/frzngdrzl.png',
                     'skins/orcas/images/icons/pop.png',
                     'skins/orcas/images/icons/thermometer-blue.png',
                     'skins/orcas/images/icons/B2n.png',
                     'skins/orcas/images/icons/moonriseset.png',
                     'skins/orcas/images/icons/blizzard.png',
                     'skins/orcas/images/icons/NW.png',
                     'skins/orcas/images/icons/snowshwrs.png',
                     'skins/orcas/images/icons/triangle-right.png',
                     'skins/orcas/images/icons/sun.png',
                     'skins/orcas/images/icons/W.png',
                     'skins/orcas/images/icons/sunmoon.png',
                     'skins/orcas/images/icons/S.png',
                     'skins/orcas/images/icons/thermometer-red.png',
                     'skins/orcas/images/icons/BD.png',
                     'skins/orcas/images/icons/E.png',
                     'skins/orcas/images/icons/BS.png',
                     'skins/orcas/images/icons/B2.png',
                     'skins/orcas/images/icons/flurries.png',
                     'skins/orcas/images/icons/OV.png',
                     'skins/orcas/images/icons/NE.png',
                     'skins/orcas/images/icons/drizzle.png',
                     'skins/orcas/images/icons/rain.png',
                     'skins/orcas/images/icons/PF+.png',
                     'skins/orcas/images/icons/B1.png',
                     'skins/orcas/images/icons/F.png',
                     'skins/orcas/images/icons/FWn.png']),
                   ('skins/orcas/js',
                    ['skins/orcas/js/foundation.stock.min.js',
                     'skins/orcas/js/foundation.min.js',
                     'skins/orcas/js/foundation',
                     'skins/orcas/js/vendor']),
                   ('skins/orcas/js/foundation',
                    ['skins/orcas/js/foundation/foundation.interchange.js',
                     'skins/orcas/js/foundation/foundation.topbar.js',
                     'skins/orcas/js/foundation/foundation.magellan.js',
                     'skins/orcas/js/foundation/foundation.alert.js',
                     'skins/orcas/js/foundation/foundation.joyride.js',
                     'skins/orcas/js/foundation/foundation.clearing.js',
                     'skins/orcas/js/foundation/foundation.js',
                     'skins/orcas/js/foundation/foundation.abide.js',
                     'skins/orcas/js/foundation/foundation.slider.js',
                     'skins/orcas/js/foundation/foundation.reveal.js',
                     'skins/orcas/js/foundation/foundation.accordion.js',
                     'skins/orcas/js/foundation/foundation.dropdown.js',
                     'skins/orcas/js/foundation/foundation.tooltip.js',
                     'skins/orcas/js/foundation/foundation.offcanvas.js',
                     'skins/orcas/js/foundation/foundation.orbit.js',
                     'skins/orcas/js/foundation/foundation.equalizer.js',
                     'skins/orcas/js/foundation/jquery.cookie.js',
                     'skins/orcas/js/foundation/foundation.tab.js']),
                   ('skins/orcas/js/vendor',
                    ['skins/orcas/js/vendor/placeholder.js',
                     'skins/orcas/js/vendor/fastclick.js',
                     'skins/orcas/js/vendor/modernizr.js',
                     'skins/orcas/js/vendor/jquery.cookie.js',
                     'skins/orcas/js/vendor/jquery.js']),
                   ('skins/orcas/RSS',
                    ['skins/orcas/RSS/weewx_rss.xml.tmpl']),
                   ]
            )
